version: "3.8"

services:
  mysql:
    image: mysql:8.0.29
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    volumes:
      - data-volumes:/var/lib/mysql

volumes: 
  data-volumes:
