version: "3.8"

services:
  mysql:
    image: mysql:latest
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
